export default [
	{
		_id: 'id-461198',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA813204780000026001234567890',
		accountCurrency: 'UAH',
		currencyCode: 980,
		correspondentBankSwift: 'none',
		correspondentBank: 'none',
	},
	{
		_id: 'id-579190',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA813204780000026001234567890',
		accountCurrency: 'USD',
		currencyCode: 840,
		correspondentBankSwift: 'CHASUS33',
		correspondentBank:
			'J.P. Morgan Chase Bank, New York 270 Park Avenue, New York, NY, 10017 USA, New York',
	},
	{
		_id: 'id-771415',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA813204780000026001234567890',
		accountCurrency: 'EUR',
		currencyCode: 978,
		correspondentBankSwift: 'COBADEFF',
		correspondentBank:
			'Commerzbank AG Neue Mainzer Strasse 32-36, 60261 Frankfurt Am Main,  Germany',
	},
	{
		_id: 'id-979431',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ ПІВДЕННИЙ',
		bankUsreou: '20953647',
		bankMfi: '328209',
		bankSwift: 'PIVDUA22',
		companyAccount: 'UA643282090000026000987654321',
		accountCurrency: 'UAH',
		currencyCode: 980,
		correspondentBankSwift: 'none',
		correspondentBank: 'none',
	},
	{
		_id: 'id-840559',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ ПІВДЕННИЙ',
		bankUsreou: '20953647',
		bankMfi: '328209',
		bankSwift: 'PIVDUA22',
		companyAccount: 'none',
		accountCurrency: 'USD',
		currencyCode: 840,
		correspondentBankSwift: 'IRVTUS3N',
		correspondentBank: 'THE BANK OF NEW YORK MELLON** New York',
	},
	{
		_id: 'id-532365',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ ПІВДЕННИЙ',
		bankUsreou: '20953647',
		bankMfi: '328209',
		bankSwift: 'PIVDUA22',
		companyAccount: 'none',
		accountCurrency: 'EUR',
		currencyCode: 978,
		correspondentBankSwift: 'COBADEFF',
		correspondentBank: 'Commerzbank AG, Kaiserplatz, D-60261 Frankfurt am Main, Germany ',
	},
	{
		_id: 'id-41487',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA953204780000000026000123456',
		accountCurrency: 'UAH',
		currencyCode: 980,
		correspondentBankSwift: 'none',
		correspondentBank: 'none',
	},
	{
		_id: 'id-813335',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA953204780000000026000654321',
		accountCurrency: 'USD',
		currencyCode: 840,
		correspondentBankSwift: 'CHASUS33',
		correspondentBank:
			'J.P. Morgan Chase Bank, New York 270 Park Avenue, New York, NY, 10017 USA, New York',
	},
	{
		_id: 'id-73200',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA953204780000000026000987654',
		accountCurrency: 'EUR',
		currencyCode: 978,
		correspondentBankSwift: 'COBADEFF',
		correspondentBank:
			'Commerzbank AG Neue Mainzer Strasse 32-36, 60261 Frankfurt Am Main,  Germany',
	},
	{
		_id: 'id-84532',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'ПАТ КБ ПРИВАТБАНК',
		bankUsreou: '14360570',
		bankMfi: '323583',
		bankSwift: 'PBANUA2X',
		companyAccount: 'UA583235830000026001236547890',
		accountCurrency: 'UAH',
		currencyCode: 980,
		correspondentBankSwift: 'none',
		correspondentBank: 'none',
	},
	{
		_id: 'id-513213',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'ПАТ КБ ПРИВАТБАНК',
		bankUsreou: '14360570',
		bankMfi: '323583',
		bankSwift: 'PBANUA2X',
		companyAccount: 'UA783235830000026000987456321',
		accountCurrency: 'USD',
		currencyCode: 840,
		correspondentBankSwift: 'CHASUS33',
		correspondentBank:
			'J.P. Morgan Chase Bank, New York 270 Park Avenue, New York, NY, 10017 USA, New York',
	},
	{
		_id: 'id-734771',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'ПАТ КБ ПРИВАТБАНК',
		bankUsreou: '14360570',
		bankMfi: '323583',
		bankSwift: 'PBANUA2X',
		companyAccount: 'none',
		accountCurrency: 'EUR',
		currencyCode: 978,
		correspondentBankSwift: 'COBADEFF',
		correspondentBank:
			'Commerzbank AG Neue Mainzer Strasse 32-36, 60261 Frankfurt Am Main,  Germany',
	},
];
