export default [
	{
		_id: 'id-344081',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA813204780000026001234567890',
		accountCurrency: 'UAH',
		currencyCode: 980,
		correspondentBankSwift: 'none',
		correspondentBank: 'none',
		bankAdress: '01030, Київ, вул. Богдана Хмельницького, 16-22',
	},
	{
		_id: 'id-78286',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA813204780000026001234567890',
		accountCurrency: 'USD',
		currencyCode: 840,
		correspondentBankSwift: 'CHASUS33',
		correspondentBank:
			'J.P. Morgan Chase Bank, New York 270 Park Avenue, New York, NY, 10017 USA, New York',
		bankAdress: '01030, Київ, вул. Богдана Хмельницького, 16-22',
	},
	{
		_id: 'id-98298',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA813204780000026001234567890',
		accountCurrency: 'EUR',
		currencyCode: 978,
		correspondentBankSwift: 'COBADEFF',
		correspondentBank:
			'Commerzbank AG Neue Mainzer Strasse 32-36, 60261 Frankfurt Am Main,  Germany',
		bankAdress: '01030, Київ, вул. Богдана Хмельницького, 16-22',
	},
	{
		_id: 'id-919239',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ ПІВДЕННИЙ',
		bankUsreou: '20953647',
		bankMfi: '328209',
		bankSwift: 'PIVDUA22',
		companyAccount: 'UA643282090000026000987654321',
		accountCurrency: 'UAH',
		currencyCode: 980,
		correspondentBankSwift: 'none',
		correspondentBank: 'none',
		bankAdress: '65059, Одеса, вул. Краснова, 6/1',
	},
	{
		_id: 'id-482214',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ ПІВДЕННИЙ',
		bankUsreou: '20953647',
		bankMfi: '328209',
		bankSwift: 'PIVDUA22',
		companyAccount: 'none',
		accountCurrency: 'USD',
		currencyCode: 840,
		correspondentBankSwift: 'IRVTUS3N',
		correspondentBank: 'THE BANK OF NEW YORK MELLON** New York',
		bankAdress: '65059, Одеса, вул. Краснова, 6/1',
	},
	{
		_id: 'id-18546',
		companyCode: 'C01',
		companyName: 'ООО Ромашка',
		companyUsreou: '12345678',
		companyAddress: {
			postalCode: '28120',
			country: 'Украина',
			region: 'Донецкая обл.',
			district: 'Донецкий р-н',
			city: 'пгт. Кабанчики',
			streetAddress: 'ул. Четыре хаты',
			numberHouse: '1',
		},
		headPosition: 'Директор',
		fullName: 'Иванов Иван Иванович',
		bankName: 'АБ ПІВДЕННИЙ',
		bankUsreou: '20953647',
		bankMfi: '328209',
		bankSwift: 'PIVDUA22',
		companyAccount: 'none',
		accountCurrency: 'EUR',
		currencyCode: 978,
		correspondentBankSwift: 'COBADEFF',
		correspondentBank: 'Commerzbank AG, Kaiserplatz, D-60261 Frankfurt am Main, Germany ',
		bankAdress: '65059, Одеса, вул. Краснова, 6/1',
	},
	{
		_id: 'id-592308',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA953204780000000026000123456',
		accountCurrency: 'UAH',
		currencyCode: 980,
		correspondentBankSwift: 'none',
		correspondentBank: 'none',
		bankAdress: '01030, Київ, вул. Богдана Хмельницького, 16-22',
	},
	{
		_id: 'id-621457',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA953204780000000026000654321',
		accountCurrency: 'USD',
		currencyCode: 840,
		correspondentBankSwift: 'CHASUS33',
		correspondentBank:
			'J.P. Morgan Chase Bank, New York 270 Park Avenue, New York, NY, 10017 USA, New York',
		bankAdress: '01030, Київ, вул. Богдана Хмельницького, 16-22',
	},
	{
		_id: 'id-858788',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'АБ УКРГАЗБАНК',
		bankUsreou: '23697280',
		bankMfi: '320478',
		bankSwift: 'UGASUAUK',
		companyAccount: 'UA953204780000000026000987654',
		accountCurrency: 'EUR',
		currencyCode: 978,
		correspondentBankSwift: 'COBADEFF',
		correspondentBank:
			'Commerzbank AG Neue Mainzer Strasse 32-36, 60261 Frankfurt Am Main,  Germany',
		bankAdress: '01030, Київ, вул. Богдана Хмельницького, 16-22',
	},
	{
		_id: 'id-576208',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'ПАТ КБ ПРИВАТБАНК',
		bankUsreou: '14360570',
		bankMfi: '323583',
		bankSwift: 'PBANUA2X',
		companyAccount: 'UA583235830000026001236547890',
		accountCurrency: 'UAH',
		currencyCode: 980,
		correspondentBankSwift: 'none',
		correspondentBank: 'none',
		bankAdress: '49094, Дніпро, вул. Набережна Перемоги, 30',
	},
	{
		_id: 'id-800773',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'ПАТ КБ ПРИВАТБАНК',
		bankUsreou: '14360570',
		bankMfi: '323583',
		bankSwift: 'PBANUA2X',
		companyAccount: 'UA783235830000026000987456321',
		accountCurrency: 'USD',
		currencyCode: 840,
		correspondentBankSwift: 'CHASUS33',
		correspondentBank:
			'J.P. Morgan Chase Bank, New York 270 Park Avenue, New York, NY, 10017 USA, New York',
		bankAdress: '49094, Дніпро, вул. Набережна Перемоги, 30',
	},
	{
		_id: 'id-937414',
		companyCode: 'C02',
		companyName: 'ООО Рога и копыта',
		companyUsreou: '87654321',
		companyAddress: {
			postalCode: '38043',
			country: 'Украина',
			region: 'Луганская обл.',
			district: 'Луганский р-н',
			city: 'с. Кукусики',
			streetAddress: 'ул. Три забора',
			numberHouse: '2',
		},
		headPosition: 'Коммерческий директор',
		fullName: 'Васильев Василий Васильевич',
		bankName: 'ПАТ КБ ПРИВАТБАНК',
		bankUsreou: '14360570',
		bankMfi: '323583',
		bankSwift: 'PBANUA2X',
		companyAccount: 'none',
		accountCurrency: 'EUR',
		currencyCode: 978,
		correspondentBankSwift: 'COBADEFF',
		correspondentBank:
			'Commerzbank AG Neue Mainzer Strasse 32-36, 60261 Frankfurt Am Main,  Germany',
		bankAdress: '49094, Дніпро, вул. Набережна Перемоги, 30',
	},
];
